name: flutter_image_crop_compress
description: A flutter plugin which compress and crop image with native (Objective-C/Kotlin) with faster speed. Support Android/iOS.
version: 0.0.2
homepage: https://github.com/arsarsars1/flutter_image_crop_compress.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
