name: flutter_image_crop_compress
description: A flutter plugin which compress and crop image with native (Objective-C/Kotlin) with faster speed. Support Android/iOS.
version: 0.0.3
homepage: https://github.com/arsarsars1/flutter_image_crop_compress.git

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
